consensus:
- host: 192.168.10.221
  port: 16789
  rpcport: 6789
  sshport: 22
  username: platon
  password: Platon123!
  blspubkey: bf21edeb2040936e3294b00bc1171d6f6f422bd6da1cf291f8884a15c5a5b68c2fb43ca6b9168f049dc1579bf07029037e4efc508d43bc7e36268a80e2f71c675302c0e23b3dbdd4e125830899cc44b323c492788fe56e12eac570a08f9c8f08
  blsprikey: efeb00965cff23db63aca7ce8c5e0ac3dbe362c92e2ece63efb0b7f7eebca73d
  id: 3058ac78b0a05637218a417e562daaca2d640afb3d142ada765650cc0bed892d91d6e8128df0a59397ea051a2d91af5b532866f411811f4fd46de068ad0e168d
  nodekey: daf5f08acea91e1901724a134d1a5651031296a2f91d544117cfc1da1947dc15
  url: http://192.168.10.221:6789
- host: 192.168.10.222
  port: 16789
  rpcport: 6789
  sshport: 22
  username: platon
  password: Platon123!
  blspubkey: 3f686e42718be2f7244c7c1ed6fce0aeb084f09d1668e6ad75aab672fb49d372dec42bede760a9c4e487fde485cd0f11994dc3223b355dd822ec499f00e67a4e0fe810dfe5aebac0a7ad3c8ad446e048ad83842719e227f183693a213680d098
  blsprikey: e7ec80183cae28e5c22288340786f78485d356b1aa3cf81aeeb9ad1795295c5f
  id: 90ceead63411f16715767459a5acce3c18825e97c76d7da4cd1ea86544f8be97f412ba9dc6a329c622f87f08e17776f93d55a06abbee5b5e2dd5c47cd2f00156
  nodekey: 3f73625656bc080b07380a29a89b8ee6c688fa5d2ef00f8982b06856d38f2410
  url: http://192.168.10.222:6789
- host: 192.168.10.223
  port: 16789
  rpcport: 6789
  sshport: 22
  username: platon
  password: Platon123!
  blspubkey: 0f86e671d706e7cbfe3e53375be684eb1d6ccd5eedd7e1384b70ab01a88158f2dbdb978ae2a27a59ca6f4a68564aeb08d49661400997a3fe57a11e4eb8a48d5ab3fe6dd27ec22d11b622a28df0fc537df722c6f7ae582b5ef79b887976d9ca09
  blsprikey: 4b858c2f80b6c19c1f60740b13a821e9a9450625c1afce3cbca0c8bf27c6f82b
  id: 2cea9abe8c2ed84a51bb2c68102adf98f2f4b28f6ed211ad613852a94d66f12d5b5839dcc0b851b1351201913794093a54fb9271c4c5532de47b89747aa9204f
  nodekey: 6abca963777a90b883526e5532d467ec912a5084d37439660d8ec9fdf11c363a
  url: http://192.168.10.223:6789
- host: 192.168.10.224
  port: 16789
  rpcport: 6789
  sshport: 22
  username: platon
  password: Platon123!
  blspubkey: 45b232cf2fbf65551d07bece502a61d22ae88083299d7cec093065fd86d6c8498051a09a981b57fe1a43480c2ecfa309447f093e1739e65c3af2aa355b15140a61a088470e87a204a380ec0ff1f435fd809f7b0ddd52f76e018eff0774a74499
  blsprikey: 88641cea5a0c9e8447986c386b64c5dcbd238b561bd3286630b88babc46ea66e
  id: f76d186ecd5f95b1f997b60e524c0eb6e492059c18ee5c2bdbd498d5e47e98868e529f8222f02d5d3e6422130c4c8b9b82ff97e67ea5f5f049dc3477624ae8e4
  nodekey: b7b1cfefcc890c7a8dd2e0eeac637004be11f2abc6bec764bcc1819b0c96773b
  url: http://192.168.10.224:6789
noconsensus:
- host: 192.168.10.222
  username: platon
  password: Platon123!
  sshport: 22
  port: 16790
  rpcport: 6790
  blspubkey: bf21edeb2040936e3294b00bc1171d6f6f422bd6da1cf291f8884a15c5a5b68c2fb43ca6b9168f049dc1579bf07029037e4efc508d43bc7e36268a80e2f71c675302c0e23b3dbdd4e125830899cc44b323c492788fe56e12eac570a08f9c8f08
  blsprikey: efeb00965cff23db63aca7ce8c5e0ac3dbe362c92e2ece63efb0b7f7eebca73d
  fail_point: github.com/PlatONnetwork/PlatON-Go/consensus/cbft/low-block-rate=return("6,0,0ee7ad2655ad3e00095414bf10406fed2c19d5b3aa514b95321bbe3c6caebd7b190683d77c874da302555c4dc4978f45b16bd62eb370b62c84544ba971b39bdd")
  id: 0ee7ad2655ad3e00095414bf10406fed2c19d5b3aa514b95321bbe3c6caebd7b190683d77c874da302555c4dc4978f45b16bd62eb370b62c84544ba971b39bdd
  nodekey: fa71985331b2cc5694a239fba7d76ffd8d42ebf3cc301e440fc5d2f73a7488e4
  url: http://192.168.10.225:6789
- host: 192.168.10.223
  username: platon
  password: Platon123!
  sshport: 22
  port: 16790
  rpcport: 6790
  blspubkey: 3f686e42718be2f7244c7c1ed6fce0aeb084f09d1668e6ad75aab672fb49d372dec42bede760a9c4e487fde485cd0f11994dc3223b355dd822ec499f00e67a4e0fe810dfe5aebac0a7ad3c8ad446e048ad83842719e227f183693a213680d098
  blsprikey: e7ec80183cae28e5c22288340786f78485d356b1aa3cf81aeeb9ad1795295c5f
  id: 2d25f7686573602334589ac2e606a3743d34fcae0c7d34c6eadc01dbecd21f349d93ec227b2c43a5f61eab7fff1e0382e8a9f61a2cce9cf8eb0730a697a98159
  nodekey: 6b2499b88a88181a1a7591555b2b5f01c07a55629040a25a0ed692577615c0ee
  url: http://192.168.10.226:6790
- host: 192.168.10.224
  username: platon
  password: Platon123!
  sshport: 22
  port: 16790
  rpcport: 6790
  fail_point: github.com/PlatONnetwork/PlatON-Go/consensus/cbft/duplicate-evidence=return("423c94bf3965e31ed5f2deab22e0a4e3a565686486cc7b4be352504fa373a4ca1ceb58e79f53f78a7cf32ca336907670eeded51e820abd4bb26b1e401dafe863")
  blspubkey: 0f86e671d706e7cbfe3e53375be684eb1d6ccd5eedd7e1384b70ab01a88158f2dbdb978ae2a27a59ca6f4a68564aeb08d49661400997a3fe57a11e4eb8a48d5ab3fe6dd27ec22d11b622a28df0fc537df722c6f7ae582b5ef79b887976d9ca09
  blsprikey: 4b858c2f80b6c19c1f60740b13a821e9a9450625c1afce3cbca0c8bf27c6f82b
  id: 423c94bf3965e31ed5f2deab22e0a4e3a565686486cc7b4be352504fa373a4ca1ceb58e79f53f78a7cf32ca336907670eeded51e820abd4bb26b1e401dafe863
  nodekey: 89d9a24db4f730652137dc3b464e675d05bed1e2e4ac5ea8053b84e3648a6ebf
  url: http://192.168.10.227:6789
